reports:
  exclude_contracts:
    - Ownable
    - Context
    - ERC20
    - SafeERC20
    - Address
    - StakingRewards
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - OpenZeppelin/openzeppelin-contracts@3.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
      - '@openzeppelin-legacy=OpenZeppelin/openzeppelin-contracts@3.3.0'
networks:
  default: avalanche-main-fork
